### ISSUE TITLE
cant find javascript-obfuscator

### ISSUE THREAD

**Issue by CorruptedL1ght** [saintdaddy/Vare-Stealer#6]

**Comment by saintdaddy** [comment]
``` 
npm install javascript-obfuscator
```
``` 
npm install --save javascript-obfuscator
```
``` 
npm install -g javascript-obfuscator
```

**Comment by saintdaddy** [comment]
> it's giving me the same problem
> 
> until I removed everything about javascript-obfuscator, but it started giving the same problem in electron-builder

make sure you have correctly downloaded visual studio build tools and all other requirements
